DATASET:
  NAME: "vcr"
  MODE: "benchmark"
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 1
  PATH: "datasets/mini_vcr"
MODEL:
  WEIGHT_IMG: "catalog://ImageNetPretrained/MSRA/R-101"
  WEIGHT_DET: "checkpoints/faster_rcnn_ckpt.pth"
  WEIGHT_SGG: "checkpoints/sg_baseline/checkpoint_0000001.pth"
  RELATION_ON: True
  ALGORITHM: "sg_baseline"
  USE_RELPN: False
  USE_FREQ_PRIOR: False
  BACKBONE:
    CONV_BODY: "R-101-C4"
    FREEZE_PARAMETER: True
  RPN:
    FREEZE_PARAMETER: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 64
  ROI_BOX_HEAD:
    NUM_CLASSES: 151
    FREEZE_PARAMETER: True
  ROI_RELATION_HEAD:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 51
    TRIPLETS_PER_IMG: 50
    IMP_FEATURE_UPDATE_STEP: 2
    MSDN_FEATURE_UPDATE_STEP: 2
    GRCNN_FEATURE_UPDATE_STEP: 2
SOLVER:
  BASE_LR: 5e-3
  MAX_ITER: 15000
  STEPS: (8000,12000)
  CHECKPOINT_PERIOD: 1000
